var dataEjercicio1 = [{ "id": 1, "marca": "Chevrolet", "modelo": "Uplander", "year": 2006, "precio": 493771 },
{ "id": 2, "marca": "Honda", "modelo": "CR-Z", "year": 2012, "precio": 633689 },
{ "id": 3, "marca": "Porsche", "modelo": "Cayman", "year": 2007, "precio": 301692 },
{ "id": 4, "marca": "BMW", "modelo": "Z3", "year": 2000, "precio": 531786 },
{ "id": 5, "marca": "Mazda", "modelo": "Protege", "year": 2001, "precio": 320731 },
{ "id": 6, "marca": "Mercedes-Benz", "modelo": "CL-Class", "year": 2004, "precio": 612056 },
{ "id": 7, "marca": "Acura", "modelo": "RDX", "year": 2008, "precio": 615200 },
{ "id": 8, "marca": "Lincoln", "modelo": "Continental", "year": 1992, "precio": 336357 },
{ "id": 9, "marca": "Dodge", "modelo": "Ram Van 3500", "year": 1999, "precio": 637890 },
{ "id": 10, "marca": "Ford", "modelo": "Escort", "year": 2000, "precio": 345444 },
{ "id": 11, "marca": "Dodge", "modelo": "Caliber", "year": 2007, "precio": 492750 },
{ "id": 12, "marca": "Mitsubishi", "modelo": "Tredia", "year": 1988, "precio": 628488 },
{ "id": 13, "marca": "Ford", "modelo": "F250", "year": 2002, "precio": 551626 },
{ "id": 14, "marca": "Mercury", "modelo": "Grand Marquis", "year": 1994, "precio": 572399 },
{ "id": 15, "marca": "Mitsubishi", "modelo": "Cordia", "year": 1987, "precio": 554989 },
{ "id": 16, "marca": "Pontiac", "modelo": "Safari", "year": 1986, "precio": 647809 },
{ "id": 17, "marca": "Nissan", "modelo": "Sentra", "year": 2006, "precio": 475856 },
{ "id": 18, "marca": "Aston Martin", "modelo": "Vanquish S", "year": 2005, "precio": 628009 },
{ "id": 19, "marca": "Toyota", "modelo": "Highlander", "year": 2003, "precio": 242158 },
{ "id": 20, "marca": "Mercedes-Benz", "modelo": "M-Class", "year": 2009, "precio": 281221 },
{ "id": 21, "marca": "Chevrolet", "modelo": "Corvette", "year": 1970, "precio": 397876 },
{ "id": 22, "marca": "Chevrolet", "modelo": "Suburban 1500", "year": 1998, "precio": 355907 },
{ "id": 23, "marca": "Dodge", "modelo": "D150", "year": 1992, "precio": 474475 },
{ "id": 24, "marca": "GMC", "modelo": "3500", "year": 1994, "precio": 249888 },
{ "id": 25, "marca": "Maserati", "modelo": "430", "year": 1989, "precio": 612092 },
{ "id": 26, "marca": "Nissan", "modelo": "Pathfinder", "year": 2008, "precio": 429358 },
{ "id": 27, "marca": "Ford", "modelo": "E-Series", "year": 2006, "precio": 329020 },
{ "id": 28, "marca": "Porsche", "modelo": "928", "year": 1995, "precio": 617904 },
{ "id": 29, "marca": "Chevrolet", "modelo": "S10", "year": 1997, "precio": 281282 },
{ "id": 30, "marca": "Porsche", "modelo": "968", "year": 1993, "precio": 272165 },
{ "id": 31, "marca": "Mercedes-Benz", "modelo": "CLS-Class", "year": 2012, "precio": 445555 },
{ "id": 32, "marca": "Lexus", "modelo": "GX", "year": 2005, "precio": 625788 },
{ "id": 33, "marca": "Buick", "modelo": "Century", "year": 1990, "precio": 284859 },
{ "id": 34, "marca": "Isuzu", "modelo": "i-370", "year": 2008, "precio": 644716 },
{ "id": 35, "marca": "Ferrari", "modelo": "599 GTB Fiorano", "year": 2007, "precio": 513586 },
{ "id": 36, "marca": "Land Rover", "modelo": "Discovery Series II", "year": 2002, "precio": 346948 },
{ "id": 37, "marca": "Volkswagen", "modelo": "Fox", "year": 1991, "precio": 532548 },
{ "id": 38, "marca": "Nissan", "modelo": "Altima", "year": 1996, "precio": 374696 },
{ "id": 39, "marca": "Toyota", "modelo": "T100 Xtra", "year": 1998, "precio": 365532 },
{ "id": 40, "marca": "Ford", "modelo": "Escape", "year": 2009, "precio": 401465 },
{ "id": 41, "marca": "Land Rover", "modelo": "Range Rover", "year": 2005, "precio": 347028 },
{ "id": 42, "marca": "Mazda", "modelo": "Miata MX-5", "year": 2002, "precio": 504721 },
{ "id": 43, "marca": "Suzuki", "modelo": "Aerio", "year": 2003, "precio": 501653 },
{ "id": 44, "marca": "Oldsmobile", "modelo": "Silhouette", "year": 1994, "precio": 300839 },
{ "id": 45, "marca": "Chevrolet", "modelo": "Camaro", "year": 1999, "precio": 294051 },
{ "id": 46, "marca": "Dodge", "modelo": "Daytona", "year": 1993, "precio": 342883 },
{ "id": 47, "marca": "Bentley", "modelo": "Continental", "year": 2006, "precio": 282169 },
{ "id": 48, "marca": "Jaguar", "modelo": "XJ Series", "year": 2004, "precio": 330416 },
{ "id": 49, "marca": "Lincoln", "modelo": "Town Car", "year": 1997, "precio": 339145 },
{ "id": 50, "marca": "Chevrolet", "modelo": "Cobalt", "year": 2005, "precio": 252232 },
{ "id": 51, "marca": "Ford", "modelo": "Mustang", "year": 1987, "precio": 458810 },
{ "id": 52, "marca": "Chrysler", "modelo": "Town & Country", "year": 2004, "precio": 376041 },
{ "id": 53, "marca": "Ford", "modelo": "F150", "year": 1998, "precio": 281628 },
{ "id": 54, "marca": "Buick", "modelo": "Regal", "year": 1991, "precio": 270521 },
{ "id": 55, "marca": "Chevrolet", "modelo": "Tracker", "year": 2004, "precio": 379292 },
{ "id": 56, "marca": "Cadillac", "modelo": "Fleetwood", "year": 1995, "precio": 399440 },
{ "id": 57, "marca": "Chevrolet", "modelo": "Corvette", "year": 1967, "precio": 293718 },
{ "id": 58, "marca": "Acura", "modelo": "RL", "year": 1998, "precio": 259113 },
{ "id": 59, "marca": "Subaru", "modelo": "Forester", "year": 2008, "precio": 308700 },
{ "id": 60, "marca": "Dodge", "modelo": "Avenger", "year": 2012, "precio": 259761 },
{ "id": 61, "marca": "Land Rover", "modelo": "LR4", "year": 2011, "precio": 629667 },
{ "id": 62, "marca": "Acura", "modelo": "RL", "year": 1996, "precio": 585029 },
{ "id": 63, "marca": "Acura", "modelo": "MDX", "year": 2005, "precio": 320335 },
{ "id": 64, "marca": "Mazda", "modelo": "Mazda2", "year": 2011, "precio": 509669 },
{ "id": 65, "marca": "Jeep", "modelo": "Liberty", "year": 2003, "precio": 528219 },
{ "id": 66, "marca": "GMC", "modelo": "3500 Club Coupe", "year": 1995, "precio": 646736 },
{ "id": 67, "marca": "Chevrolet", "modelo": "Camaro", "year": 1973, "precio": 327912 },
{ "id": 68, "marca": "Subaru", "modelo": "Impreza", "year": 1993, "precio": 382605 },
{ "id": 69, "marca": "Chevrolet", "modelo": "S10", "year": 2001, "precio": 388856 },
{ "id": 70, "marca": "Lincoln", "modelo": "Continental", "year": 1998, "precio": 612242 },
{ "id": 71, "marca": "Hyundai", "modelo": "Tiburon", "year": 2006, "precio": 445736 },
{ "id": 72, "marca": "Chevrolet", "modelo": "Astro", "year": 2002, "precio": 319049 },
{ "id": 73, "marca": "Subaru", "modelo": "Justy", "year": 1988, "precio": 392146 },
{ "id": 74, "marca": "Ford", "modelo": "E150", "year": 2008, "precio": 423920 },
{ "id": 75, "marca": "Ford", "modelo": "Courier", "year": 1988, "precio": 475610 },
{ "id": 76, "marca": "Ford", "modelo": "Club Wagon", "year": 1992, "precio": 554363 },
{ "id": 77, "marca": "Chevrolet", "modelo": "Cavalier", "year": 2003, "precio": 401492 },
{ "id": 78, "marca": "Porsche", "modelo": "Boxster", "year": 1998, "precio": 548856 },
{ "id": 79, "marca": "Porsche", "modelo": "911", "year": 1987, "precio": 634168 },
{ "id": 80, "marca": "Acura", "modelo": "Legend", "year": 1987, "precio": 614229 },
{ "id": 81, "marca": "Mitsubishi", "modelo": "Galant", "year": 2012, "precio": 386235 },
{ "id": 82, "marca": "Ford", "modelo": "F150", "year": 2003, "precio": 591166 },
{ "id": 83, "marca": "GMC", "modelo": "Sonoma Club Coupe", "year": 1994, "precio": 647156 },
{ "id": 84, "marca": "Chevrolet", "modelo": "Corvette", "year": 2000, "precio": 287478 },
{ "id": 85, "marca": "Ram", "modelo": "Dakota", "year": 2011, "precio": 285054 },
{ "id": 86, "marca": "Bentley", "modelo": "Brooklands", "year": 2009, "precio": 466826 },
{ "id": 87, "marca": "Ford", "modelo": "F250", "year": 1999, "precio": 583874 },
{ "id": 88, "marca": "Scion", "modelo": "FR-S", "year": 2013, "precio": 249080 },
{ "id": 89, "marca": "Kia", "modelo": "Amanti", "year": 2006, "precio": 493760 },
{ "id": 90, "marca": "Land Rover", "modelo": "Defender 90", "year": 1995, "precio": 478462 },
{ "id": 91, "marca": "Mazda", "modelo": "Navajo", "year": 1993, "precio": 259421 },
{ "id": 92, "marca": "Pontiac", "modelo": "Sunbird", "year": 1991, "precio": 643297 },
{ "id": 93, "marca": "Ford", "modelo": "E150", "year": 2003, "precio": 382468 },
{ "id": 94, "marca": "Saab", "modelo": "9-5", "year": 1999, "precio": 261896 },
{ "id": 95, "marca": "Pontiac", "modelo": "Sunbird", "year": 1984, "precio": 278495 },
{ "id": 96, "marca": "Mazda", "modelo": "B-Series", "year": 1996, "precio": 381492 },
{ "id": 97, "marca": "GMC", "modelo": "Savana 1500", "year": 2003, "precio": 334750 },
{ "id": 98, "marca": "Hyundai", "modelo": "Tucson", "year": 2008, "precio": 252520 },
{ "id": 99, "marca": "Chevrolet", "modelo": "Equinox", "year": 2010, "precio": 232914 },
{ "id": 100, "marca": "GMC", "modelo": "Savana 1500", "year": 1997, "precio": 481749 },
{ "id": 101, "marca": "GMC", "modelo": "Sierra", "year": 2007, "precio": 553457 },
{ "id": 102, "marca": "Mercedes-Benz", "modelo": "CLK-Class", "year": 2007, "precio": 300539 },
{ "id": 103, "marca": "Audi", "modelo": "4000", "year": 1987, "precio": 569795 },
{ "id": 104, "marca": "Mitsubishi", "modelo": "Chariot", "year": 1996, "precio": 564793 },
{ "id": 105, "marca": "Mazda", "modelo": "MX-3", "year": 1996, "precio": 385851 },
{ "id": 106, "marca": "Toyota", "modelo": "Xtra", "year": 1994, "precio": 481096 },
{ "id": 107, "marca": "Mercedes-Benz", "modelo": "SLK-Class", "year": 2006, "precio": 378457 },
{ "id": 108, "marca": "Holden", "modelo": "VS Commodore", "year": 1997, "precio": 448681 },
{ "id": 109, "marca": "Acura", "modelo": "SLX", "year": 1998, "precio": 322074 },
{ "id": 110, "marca": "Chevrolet", "modelo": "Impala", "year": 2001, "precio": 333075 },
{ "id": 111, "marca": "Chevrolet", "modelo": "HHR", "year": 2008, "precio": 485584 },
{ "id": 112, "marca": "BMW", "modelo": "3 Series", "year": 1992, "precio": 392025 },
{ "id": 113, "marca": "Peugeot", "modelo": "207", "year": 2006, "precio": 333183 },
{ "id": 114, "marca": "Land Rover", "modelo": "Discovery", "year": 2000, "precio": 553243 },
{ "id": 115, "marca": "Hyundai", "modelo": "Equus", "year": 2011, "precio": 583912 },
{ "id": 116, "marca": "MINI", "modelo": "Cooper Clubman", "year": 2009, "precio": 294557 },
{ "id": 117, "marca": "Dodge", "modelo": "Neon", "year": 1996, "precio": 562351 },
{ "id": 118, "marca": "Chevrolet", "modelo": "Cobalt", "year": 2006, "precio": 288335 },
{ "id": 119, "marca": "Mazda", "modelo": "MX-6", "year": 1997, "precio": 626746 },
{ "id": 120, "marca": "Mitsubishi", "modelo": "Eclipse", "year": 2007, "precio": 372425 },
{ "id": 121, "marca": "Lincoln", "modelo": "Mark VIII", "year": 1994, "precio": 584270 },
{ "id": 122, "marca": "Jaguar", "modelo": "XJ", "year": 2009, "precio": 590469 },
{ "id": 123, "marca": "Dodge", "modelo": "Magnum", "year": 2008, "precio": 348672 },
{ "id": 124, "marca": "Volkswagen", "modelo": "Golf", "year": 2005, "precio": 309348 },
{ "id": 125, "marca": "Mazda", "modelo": "Familia", "year": 1987, "precio": 579204 },
{ "id": 126, "marca": "Ford", "modelo": "Escort", "year": 1997, "precio": 262363 },
{ "id": 127, "marca": "Lamborghini", "modelo": "Gallardo", "year": 2007, "precio": 354881 },
{ "id": 128, "marca": "Alfa Romeo", "modelo": "164", "year": 1995, "precio": 432528 },
{ "id": 129, "marca": "Toyota", "modelo": "Celica", "year": 1999, "precio": 575597 },
{ "id": 130, "marca": "Suzuki", "modelo": "Equator", "year": 2011, "precio": 322793 },
{ "id": 131, "marca": "Audi", "modelo": "A4", "year": 2005, "precio": 615355 },
{ "id": 132, "marca": "GMC", "modelo": "Yukon XL 2500", "year": 2004, "precio": 332151 },
{ "id": 133, "marca": "Pontiac", "modelo": "Grand Prix", "year": 1972, "precio": 607207 },
{ "id": 134, "marca": "Infiniti", "modelo": "EX", "year": 2010, "precio": 616163 },
{ "id": 135, "marca": "Ford", "modelo": "Bronco II", "year": 1988, "precio": 280204 },
{ "id": 136, "marca": "Porsche", "modelo": "928", "year": 1986, "precio": 408314 },
{ "id": 137, "marca": "Chevrolet", "modelo": "Prizm", "year": 2002, "precio": 640072 },
{ "id": 138, "marca": "Mitsubishi", "modelo": "Chariot", "year": 1989, "precio": 569416 },
{ "id": 139, "marca": "Pontiac", "modelo": "Firebird", "year": 2001, "precio": 561163 },
{ "id": 140, "marca": "Ferrari", "modelo": "458 Italia", "year": 2010, "precio": 506964 },
{ "id": 141, "marca": "Oldsmobile", "modelo": "Ciera", "year": 1992, "precio": 583803 },
{ "id": 142, "marca": "Cadillac", "modelo": "XLR-V", "year": 2008, "precio": 494688 },
{ "id": 143, "marca": "Mitsubishi", "modelo": "Pajero", "year": 1991, "precio": 411576 },
{ "id": 144, "marca": "GMC", "modelo": "1500", "year": 1997, "precio": 402952 },
{ "id": 145, "marca": "Kia", "modelo": "Sportage", "year": 2001, "precio": 531023 },
{ "id": 146, "marca": "Pontiac", "modelo": "Grand Prix Turbo", "year": 1990, "precio": 614074 },
{ "id": 147, "marca": "Mercedes-Benz", "modelo": "300E", "year": 1993, "precio": 392633 },
{ "id": 148, "marca": "Chevrolet", "modelo": "Silverado", "year": 2008, "precio": 339443 },
{ "id": 149, "marca": "Audi", "modelo": "A6", "year": 2012, "precio": 330588 },
{ "id": 150, "marca": "Mercedes-Benz", "modelo": "E-Class", "year": 1994, "precio": 487702 },
{ "id": 151, "marca": "Ford", "modelo": "Thunderbird", "year": 1977, "precio": 272670 },
{ "id": 152, "marca": "Kia", "modelo": "Mohave/Borrego", "year": 2009, "precio": 482323 },
{ "id": 153, "marca": "Ford", "modelo": "E250", "year": 2012, "precio": 455755 },
{ "id": 154, "marca": "Lincoln", "modelo": "Mark LT", "year": 2007, "precio": 248022 },
{ "id": 155, "marca": "Mazda", "modelo": "Mazda6", "year": 2012, "precio": 621257 },
{ "id": 156, "marca": "Ford", "modelo": "Escort", "year": 1987, "precio": 609925 },
{ "id": 157, "marca": "Toyota", "modelo": "Avalon", "year": 2006, "precio": 275839 },
{ "id": 158, "marca": "Plymouth", "modelo": "Breeze", "year": 1998, "precio": 520469 },
{ "id": 159, "marca": "Jeep", "modelo": "Commander", "year": 2010, "precio": 488321 },
{ "id": 160, "marca": "Ford", "modelo": "Fusion", "year": 2006, "precio": 422604 },
{ "id": 161, "marca": "BMW", "modelo": "325", "year": 2004, "precio": 515860 },
{ "id": 162, "marca": "Jeep", "modelo": "Grand Cherokee", "year": 1999, "precio": 230334 },
{ "id": 163, "marca": "Dodge", "modelo": "Intrepid", "year": 1997, "precio": 450413 },
{ "id": 164, "marca": "Chevrolet", "modelo": "Monte Carlo", "year": 1999, "precio": 266578 },
{ "id": 165, "marca": "Maserati", "modelo": "Spyder", "year": 2002, "precio": 460099 },
{ "id": 166, "marca": "Acura", "modelo": "NSX", "year": 2000, "precio": 394031 },
{ "id": 167, "marca": "Acura", "modelo": "RL", "year": 1997, "precio": 288671 },
{ "id": 168, "marca": "Mercedes-Benz", "modelo": "S-Class", "year": 1986, "precio": 414837 },
{ "id": 169, "marca": "Mazda", "modelo": "Tribute", "year": 2001, "precio": 308345 },
{ "id": 170, "marca": "Hyundai", "modelo": "Santa Fe", "year": 2008, "precio": 372083 },
{ "id": 171, "marca": "Isuzu", "modelo": "Oasis", "year": 1998, "precio": 473673 },
{ "id": 172, "marca": "Porsche", "modelo": "928", "year": 1995, "precio": 404673 },
{ "id": 173, "marca": "BMW", "modelo": "X5", "year": 2011, "precio": 393816 },
{ "id": 174, "marca": "Honda", "modelo": "Accord", "year": 1988, "precio": 479521 },
{ "id": 175, "marca": "Mitsubishi", "modelo": "Endeavor", "year": 2004, "precio": 345906 },
{ "id": 176, "marca": "Chevrolet", "modelo": "Corvette", "year": 1975, "precio": 499853 },
{ "id": 177, "marca": "Mercury", "modelo": "Marquis", "year": 1985, "precio": 293528 },
{ "id": 178, "marca": "Toyota", "modelo": "Tundra", "year": 2001, "precio": 528837 },
{ "id": 179, "marca": "Mitsubishi", "modelo": "Montero", "year": 1999, "precio": 640366 },
{ "id": 180, "marca": "Honda", "modelo": "S2000", "year": 2009, "precio": 476550 },
{ "id": 181, "marca": "Volkswagen", "modelo": "rio", "year": 1999, "precio": 642453 },
{ "id": 182, "marca": "Kia", "modelo": "Sportage", "year": 2009, "precio": 460692 },
{ "id": 183, "marca": "Porsche", "modelo": "Panamera", "year": 2012, "precio": 343023 },
{ "id": 184, "marca": "Jensen", "modelo": "Interceptor", "year": 1967, "precio": 307085 },
{ "id": 185, "marca": "Ford", "modelo": "E-Series", "year": 1987, "precio": 613822 },
{ "id": 186, "marca": "Mercedes-Benz", "modelo": "CLS-Class", "year": 2009, "precio": 635290 },
{ "id": 187, "marca": "GMC", "modelo": "Sierra Hybrid", "year": 2006, "precio": 292568 },
{ "id": 188, "marca": "Dodge", "modelo": "Grand Caravan", "year": 1997, "precio": 330219 },
{ "id": 189, "marca": "Ford", "modelo": "Crown Victoria", "year": 1992, "precio": 637375 },
{ "id": 190, "marca": "Ford", "modelo": "Taurus", "year": 2008, "precio": 442467 },
{ "id": 191, "marca": "Kia", "modelo": "Rio", "year": 2005, "precio": 250413 },
{ "id": 192, "marca": "Mercedes-Benz", "modelo": "C-Class", "year": 2000, "precio": 297939 },
{ "id": 193, "marca": "Mazda", "modelo": "B-Series", "year": 1991, "precio": 567219 },
{ "id": 194, "marca": "MINI", "modelo": "Cooper", "year": 2006, "precio": 557637 },
{ "id": 195, "marca": "Nissan", "modelo": "Quest", "year": 2011, "precio": 394316 },
{ "id": 196, "marca": "Chrysler", "modelo": "300", "year": 2007, "precio": 319093 },
{ "id": 197, "marca": "Mercedes-Benz", "modelo": "R-Class", "year": 2010, "precio": 252774 },
{ "id": 198, "marca": "Audi", "modelo": "4000s", "year": 1986, "precio": 605546 },
{ "id": 199, "marca": "Mitsubishi", "modelo": "Galant", "year": 1998, "precio": 376602 },
{ "id": 200, "marca": "Chevrolet", "modelo": "Silverado 1500", "year": 2009, "precio": 476311 }];


var dataEjercicio2 = [
   {
      "id": 30,
      "title": "Key Holder",
      "description": "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
      "price": 30,
      "discountPercentage": 2.92,
      "rating": 4.92,
      "stock": 54,
      "brand": "Golden",
      "category": "home-decoration",
      "thumbnail": "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/30/1.jpg",
         "https://i.dummyjson.com/data/products/30/2.jpg",
         "https://i.dummyjson.com/data/products/30/3.jpg",
         "https://i.dummyjson.com/data/products/30/thumbnail.jpg"
      ]
   },
   {
      "id": 6,
      "title": "MacBook Pro",
      "description": "MacBook Pro 2021 with mini-LED display may launch between September, November",
      "price": 1749,
      "discountPercentage": 11.02,
      "rating": 4.57,
      "stock": 83,
      "brand": "Apple",
      "category": "laptops",
      "thumbnail": "https://i.dummyjson.com/data/products/6/thumbnail.png",
      "images": [
         "https://i.dummyjson.com/data/products/6/1.png",
         "https://i.dummyjson.com/data/products/6/2.jpg",
         "https://i.dummyjson.com/data/products/6/3.png",
         "https://i.dummyjson.com/data/products/6/4.jpg"
      ]
   },
   {
      "id": 2,
      "title": "iPhone X",
      "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
      "price": 899,
      "discountPercentage": 17.94,
      "rating": 4.44,
      "stock": 34,
      "brand": "Apple",
      "category": "smartphones",
      "thumbnail": "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/2/1.jpg",
         "https://i.dummyjson.com/data/products/2/2.jpg",
         "https://i.dummyjson.com/data/products/2/3.jpg",
         "https://i.dummyjson.com/data/products/2/thumbnail.jpg"
      ]
   },
   {
      "id": 3,
      "title": "Samsung Universe 9",
      "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
      "price": 1249,
      "discountPercentage": 15.46,
      "rating": 4.09,
      "stock": 36,
      "brand": "Samsung",
      "category": "smartphones",
      "thumbnail": "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/3/1.jpg"
      ]
   },
   {
      "id": 4,
      "title": "OPPOF19",
      "description": "OPPO F19 is officially announced on April 2021.",
      "price": 280,
      "discountPercentage": 17.91,
      "rating": 4.3,
      "stock": 123,
      "brand": "OPPO",
      "category": "smartphones",
      "thumbnail": "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/4/1.jpg",
         "https://i.dummyjson.com/data/products/4/2.jpg",
         "https://i.dummyjson.com/data/products/4/3.jpg",
         "https://i.dummyjson.com/data/products/4/4.jpg",
         "https://i.dummyjson.com/data/products/4/thumbnail.jpg"
      ]
   },
   {
      "id": 5,
      "title": "Huawei P30",
      "description": "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
      "price": 499,
      "discountPercentage": 10.58,
      "rating": 4.09,
      "stock": 32,
      "brand": "Huawei",
      "category": "smartphones",
      "thumbnail": "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/5/1.jpg",
         "https://i.dummyjson.com/data/products/5/2.jpg",
         "https://i.dummyjson.com/data/products/5/3.jpg"
      ]
   },
   {
      "id": 7,
      "title": "Samsung Galaxy Book",
      "description": "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
      "price": 1499,
      "discountPercentage": 4.15,
      "rating": 4.25,
      "stock": 50,
      "brand": "Samsung",
      "category": "laptops",
      "thumbnail": "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/7/1.jpg",
         "https://i.dummyjson.com/data/products/7/2.jpg",
         "https://i.dummyjson.com/data/products/7/3.jpg",
         "https://i.dummyjson.com/data/products/7/thumbnail.jpg"
      ]
   },
   {
      "id": 1,
      "title": "iPhone 9",
      "description": "An apple mobile which is nothing like apple",
      "price": 549,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "smartphones",
      "thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/1/1.jpg",
         "https://i.dummyjson.com/data/products/1/2.jpg",
         "https://i.dummyjson.com/data/products/1/3.jpg",
         "https://i.dummyjson.com/data/products/1/4.jpg",
         "https://i.dummyjson.com/data/products/1/thumbnail.jpg"
      ]
   },
   {
      "id": 8,
      "title": "Microsoft Surface Laptop 4",
      "description": "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
      "price": 1499,
      "discountPercentage": 10.23,
      "rating": 4.43,
      "stock": 68,
      "brand": "Microsoft Surface",
      "category": "laptops",
      "thumbnail": "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/8/1.jpg",
         "https://i.dummyjson.com/data/products/8/2.jpg",
         "https://i.dummyjson.com/data/products/8/3.jpg",
         "https://i.dummyjson.com/data/products/8/4.jpg",
         "https://i.dummyjson.com/data/products/8/thumbnail.jpg"
      ]
   },
   {
      "id": 9,
      "title": "Infinix INBOOK",
      "description": "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
      "price": 1099,
      "discountPercentage": 11.83,
      "rating": 4.54,
      "stock": 96,
      "brand": "Infinix",
      "category": "laptops",
      "thumbnail": "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/9/1.jpg",
         "https://i.dummyjson.com/data/products/9/2.png",
         "https://i.dummyjson.com/data/products/9/3.png",
         "https://i.dummyjson.com/data/products/9/4.jpg",
         "https://i.dummyjson.com/data/products/9/thumbnail.jpg"
      ]
   },
   {
      "id": 10,
      "title": "HP Pavilion 15-DK1056WM",
      "description": "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
      "price": 1099,
      "discountPercentage": 6.18,
      "rating": 4.43,
      "stock": 89,
      "brand": "HP Pavilion",
      "category": "laptops",
      "thumbnail": "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
      "images": [
         "https://i.dummyjson.com/data/products/10/1.jpg",
         "https://i.dummyjson.com/data/products/10/2.jpg",
         "https://i.dummyjson.com/data/products/10/3.jpg",
         "https://i.dummyjson.com/data/products/10/thumbnail.jpeg"
      ]
   },
   {
      "id": 11,
      "title": "perfume Oil",
      "description": "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
      "price": 13,
      "discountPercentage": 8.4,
      "rating": 4.26,
      "stock": 65,
      "brand": "Impression of Acqua Di Gio",
      "category": "fragrances",
      "thumbnail": "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/11/1.jpg",
         "https://i.dummyjson.com/data/products/11/2.jpg",
         "https://i.dummyjson.com/data/products/11/3.jpg",
         "https://i.dummyjson.com/data/products/11/thumbnail.jpg"
      ]
   },
   {
      "id": 12,
      "title": "Brown Perfume",
      "description": "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
      "price": 40,
      "discountPercentage": 15.66,
      "rating": 4,
      "stock": 52,
      "brand": "Royal_Mirage",
      "category": "fragrances",
      "thumbnail": "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/12/1.jpg",
         "https://i.dummyjson.com/data/products/12/2.jpg",
         "https://i.dummyjson.com/data/products/12/3.png",
         "https://i.dummyjson.com/data/products/12/4.jpg",
         "https://i.dummyjson.com/data/products/12/thumbnail.jpg"
      ]
   },
   {
      "id": 13,
      "title": "Fog Scent Xpressio Perfume",
      "description": "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
      "price": 13,
      "discountPercentage": 8.14,
      "rating": 4.59,
      "stock": 61,
      "brand": "Fog Scent Xpressio",
      "category": "fragrances",
      "thumbnail": "https://i.dummyjson.com/data/products/13/thumbnail.webp",
      "images": [
         "https://i.dummyjson.com/data/products/13/1.jpg",
         "https://i.dummyjson.com/data/products/13/2.png",
         "https://i.dummyjson.com/data/products/13/3.jpg",
         "https://i.dummyjson.com/data/products/13/4.jpg",
         "https://i.dummyjson.com/data/products/13/thumbnail.webp"
      ]
   },
   {
      "id": 14,
      "title": "Non-Alcoholic Concentrated Perfume Oil",
      "description": "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
      "price": 120,
      "discountPercentage": 15.6,
      "rating": 4.21,
      "stock": 114,
      "brand": "Al Munakh",
      "category": "fragrances",
      "thumbnail": "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/14/1.jpg",
         "https://i.dummyjson.com/data/products/14/2.jpg",
         "https://i.dummyjson.com/data/products/14/3.jpg",
         "https://i.dummyjson.com/data/products/14/thumbnail.jpg"
      ]
   },
   {
      "id": 15,
      "title": "Eau De Perfume Spray",
      "description": "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
      "price": 30,
      "discountPercentage": 10.99,
      "rating": 4.7,
      "stock": 105,
      "brand": "Lord - Al-Rehab",
      "category": "fragrances",
      "thumbnail": "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/15/1.jpg",
         "https://i.dummyjson.com/data/products/15/2.jpg",
         "https://i.dummyjson.com/data/products/15/3.jpg",
         "https://i.dummyjson.com/data/products/15/4.jpg",
         "https://i.dummyjson.com/data/products/15/thumbnail.jpg"
      ]
   },
   {
      "id": 16,
      "title": "Hyaluronic Acid Serum",
      "description": "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
      "price": 19,
      "discountPercentage": 13.31,
      "rating": 4.83,
      "stock": 110,
      "brand": "L'Oreal Paris",
      "category": "skincare",
      "thumbnail": "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/16/1.png",
         "https://i.dummyjson.com/data/products/16/2.webp",
         "https://i.dummyjson.com/data/products/16/3.jpg",
         "https://i.dummyjson.com/data/products/16/4.jpg",
         "https://i.dummyjson.com/data/products/16/thumbnail.jpg"
      ]
   },
   {
      "id": 17,
      "title": "Tree Oil 30ml",
      "description": "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
      "price": 12,
      "discountPercentage": 4.09,
      "rating": 4.52,
      "stock": 78,
      "brand": "Hemani Tea",
      "category": "skincare",
      "thumbnail": "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/17/1.jpg",
         "https://i.dummyjson.com/data/products/17/2.jpg",
         "https://i.dummyjson.com/data/products/17/3.jpg",
         "https://i.dummyjson.com/data/products/17/thumbnail.jpg"
      ]
   },
   {
      "id": 18,
      "title": "Oil Free Moisturizer 100ml",
      "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
      "price": 40,
      "discountPercentage": 13.1,
      "rating": 4.56,
      "stock": 88,
      "brand": "Dermive",
      "category": "skincare",
      "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/18/1.jpg",
         "https://i.dummyjson.com/data/products/18/2.jpg",
         "https://i.dummyjson.com/data/products/18/3.jpg",
         "https://i.dummyjson.com/data/products/18/4.jpg",
         "https://i.dummyjson.com/data/products/18/thumbnail.jpg"
      ]
   },
   {
      "id": 19,
      "title": "Skin Beauty Serum.",
      "description": "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
      "price": 46,
      "discountPercentage": 10.68,
      "rating": 4.42,
      "stock": 54,
      "brand": "ROREC White Rice",
      "category": "skincare",
      "thumbnail": "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/19/1.jpg",
         "https://i.dummyjson.com/data/products/19/2.jpg",
         "https://i.dummyjson.com/data/products/19/3.png",
         "https://i.dummyjson.com/data/products/19/thumbnail.jpg"
      ]
   },
   {
      "id": 20,
      "title": "Freckle Treatment Cream- 15gm",
      "description": "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
      "price": 70,
      "discountPercentage": 16.99,
      "rating": 4.06,
      "stock": 140,
      "brand": "Fair & Clear",
      "category": "skincare",
      "thumbnail": "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/20/1.jpg",
         "https://i.dummyjson.com/data/products/20/2.jpg",
         "https://i.dummyjson.com/data/products/20/3.jpg",
         "https://i.dummyjson.com/data/products/20/4.jpg",
         "https://i.dummyjson.com/data/products/20/thumbnail.jpg"
      ]
   },
   {
      "id": 21,
      "title": "- Daal Masoor 500 grams",
      "description": "Fine quality Branded Product Keep in a cool and dry place",
      "price": 20,
      "discountPercentage": 4.81,
      "rating": 4.44,
      "stock": 133,
      "brand": "Saaf & Khaas",
      "category": "groceries",
      "thumbnail": "https://i.dummyjson.com/data/products/21/thumbnail.png",
      "images": [
         "https://i.dummyjson.com/data/products/21/1.png",
         "https://i.dummyjson.com/data/products/21/2.jpg",
         "https://i.dummyjson.com/data/products/21/3.jpg"
      ]
   },
   {
      "id": 22,
      "title": "Elbow Macaroni - 400 gm",
      "description": "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
      "price": 14,
      "discountPercentage": 15.58,
      "rating": 4.57,
      "stock": 146,
      "brand": "Bake Parlor Big",
      "category": "groceries",
      "thumbnail": "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/22/1.jpg",
         "https://i.dummyjson.com/data/products/22/2.jpg",
         "https://i.dummyjson.com/data/products/22/3.jpg"
      ]
   },
   {
      "id": 23,
      "title": "Orange Essence Food Flavou",
      "description": "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
      "price": 14,
      "discountPercentage": 8.04,
      "rating": 4.85,
      "stock": 26,
      "brand": "Baking Food Items",
      "category": "groceries",
      "thumbnail": "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/23/1.jpg",
         "https://i.dummyjson.com/data/products/23/2.jpg",
         "https://i.dummyjson.com/data/products/23/3.jpg",
         "https://i.dummyjson.com/data/products/23/4.jpg",
         "https://i.dummyjson.com/data/products/23/thumbnail.jpg"
      ]
   },
   {
      "id": 24,
      "title": "cereals muesli fruit nuts",
      "description": "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
      "price": 46,
      "discountPercentage": 16.8,
      "rating": 4.94,
      "stock": 113,
      "brand": "fauji",
      "category": "groceries",
      "thumbnail": "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/24/1.jpg",
         "https://i.dummyjson.com/data/products/24/2.jpg",
         "https://i.dummyjson.com/data/products/24/3.jpg",
         "https://i.dummyjson.com/data/products/24/4.jpg",
         "https://i.dummyjson.com/data/products/24/thumbnail.jpg"
      ]
   },
   {
      "id": 25,
      "title": "Gulab Powder 50 Gram",
      "description": "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
      "price": 70,
      "discountPercentage": 13.58,
      "rating": 4.87,
      "stock": 47,
      "brand": "Dry Rose",
      "category": "groceries",
      "thumbnail": "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/25/1.png",
         "https://i.dummyjson.com/data/products/25/2.jpg",
         "https://i.dummyjson.com/data/products/25/3.png",
         "https://i.dummyjson.com/data/products/25/4.jpg",
         "https://i.dummyjson.com/data/products/25/thumbnail.jpg"
      ]
   },
   {
      "id": 26,
      "title": "Plant Hanger For Home",
      "description": "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
      "price": 41,
      "discountPercentage": 17.86,
      "rating": 4.08,
      "stock": 131,
      "brand": "Boho Decor",
      "category": "home-decoration",
      "thumbnail": "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/26/1.jpg",
         "https://i.dummyjson.com/data/products/26/2.jpg",
         "https://i.dummyjson.com/data/products/26/3.jpg",
         "https://i.dummyjson.com/data/products/26/4.jpg",
         "https://i.dummyjson.com/data/products/26/5.jpg",
         "https://i.dummyjson.com/data/products/26/thumbnail.jpg"
      ]
   },
   {
      "id": 27,
      "title": "Flying Wooden Bird",
      "description": "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
      "price": 51,
      "discountPercentage": 15.58,
      "rating": 4.41,
      "stock": 17,
      "brand": "Flying Wooden",
      "category": "home-decoration",
      "thumbnail": "https://i.dummyjson.com/data/products/27/thumbnail.webp",
      "images": [
         "https://i.dummyjson.com/data/products/27/1.jpg",
         "https://i.dummyjson.com/data/products/27/2.jpg",
         "https://i.dummyjson.com/data/products/27/3.jpg",
         "https://i.dummyjson.com/data/products/27/4.jpg",
         "https://i.dummyjson.com/data/products/27/thumbnail.webp"
      ]
   },
   {
      "id": 28,
      "title": "3D Embellishment Art Lamp",
      "description": "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
      "price": 20,
      "discountPercentage": 16.49,
      "rating": 4.82,
      "stock": 54,
      "brand": "LED Lights",
      "category": "home-decoration",
      "thumbnail": "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
      "images": [
         "https://i.dummyjson.com/data/products/28/1.jpg",
         "https://i.dummyjson.com/data/products/28/2.jpg",
         "https://i.dummyjson.com/data/products/28/3.png",
         "https://i.dummyjson.com/data/products/28/4.jpg",
         "https://i.dummyjson.com/data/products/28/thumbnail.jpg"
      ]
   },
   {
      "id": 29,
      "title": "Handcraft Chinese style",
      "description": "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
      "price": 60,
      "discountPercentage": 15.34,
      "rating": 4.44,
      "stock": 7,
      "brand": "luxury palace",
      "category": "home-decoration",
      "thumbnail": "https://i.dummyjson.com/data/products/29/thumbnail.webp",
      "images": [
         "https://i.dummyjson.com/data/products/29/1.jpg",
         "https://i.dummyjson.com/data/products/29/2.jpg",
         "https://i.dummyjson.com/data/products/29/3.webp",
         "https://i.dummyjson.com/data/products/29/4.webp",
         "https://i.dummyjson.com/data/products/29/thumbnail.webp"
      ]
   }
];